const router = require("express").Router()
const userController = require('../controllers/User')
const auth = require('../middlewares/auth.js')
const authAdmin = require("../middlewares/authAdmin")
router.post('/register',userController.register)
router.post('/login',userController.login)
router.get('/logout',userController.logout)

router.get('/refresh_token',userController.refreshToken)
router.get('/getUser/',auth,  userController.getUser)
router.get('/users' ,auth, authAdmin ,userController.getAllUsers) 
router.get('/getAll' , userController.getAll) 
router.delete('/deleteusers/:id' ,auth, authAdmin,userController.deleteUsers)  
router.delete('/deleteuser/:id' ,auth,userController.deleteUsers)  
router.put('/updateUser/:id'  , auth ,userController.UpdateUser)
router.post('/verifyAccount' , auth ,userController.verifyMail)
router.post('/changePassword' , auth,userController.updatePassword)
router.post('/updateLocation' ,auth ,userController.sendLocation)
module.exports = router 
